### ISSUE TITLE
Import AMD Module Error

### ISSUE THREAD

**Issue by zawilliams** [steida/este-todomvc#13]
Hey @steida,

I was trying to import an npm package after installing it via `npm install` using `import Scribe from 'scribe-editor'`. The package is located here: https://www.npmjs.com/package/scribe-editor

If I run the dev server with `gulp`, whenever I import the package, for example, in the todos.jsx, the server crashes and I get the following error:

```
[piping] can't execute file: /Users/zacharywilliams/Development/test/src/server/index.js
[piping] error given was: ReferenceError: define is not defined
    at Object.<anonymous> (/Users/<username>/Development/test/node_modules/scribe-editor/src/scribe.js:1:63)
```

The issue seems to be with `define is not defined` - the scribe-editor package is all AMD style but for some reason webpack is getting angry with it.

Any ideas? I feel like I'm missing something obvious.

**Comment by steida** [comment]
Unfortunatelly I am not using AMD so I don't know. Check http://webpack.github.io/docs/ and feel free to send pull request.

**Comment by zawilliams** [comment]
Checked there already. Thanks anyway.
