### ISSUE TITLE
It works with io.js

### ISSUE THREAD

**Issue by frol** [steida/este-todomvc#17]
I have tested this demo with io.js 2.2.1 and it works. Thus, it is safe to add it to `engines` section of `package.json`, I guess.

**Comment by steida** [comment]
Please send pull request.

**Comment by steida** [comment]
This demo is not maintained anymore. Do you want to became maintainer?

**Comment by frol** [comment]
@steida I'm new to este and JS server development, so I'm not a perfect match.

**Comment by steida** [comment]
So it's challange : ) It's easy, just take a look how current Este.js looks like, and update todo-mvc by that. You will learn a lot and open source makes people famous.

**Comment by frol** [comment]
@steida I will contact you if I get nice results! :)

**Comment by steida** [comment]
Go for it :) Open source ecosystem thanks you!
